# TP PYTHON PARA CIENCIA DE DATOS

### Importamos las librerias que se utilizaran

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### Cargamos el Dataset 
- Dataset: Impacto de la IA Generativa estudiantes y profesionales

| Columna | Descripción |
|---|---|
| `User_ID` | Usuario |
| `Age` | Edad |
| `Gender` | Genero |
| `Country` | Pais |
| `User_Type` | A que se dedica |
| `Education_Level` | Nivel educativo |
| `Profession` | Profesion |
| `Monthly_Income` | Ingreso mensual |
| `AI_Tool` | Herramienta de IA que utiliza |
| `AI_Purpose` | Para que utiliza la IA |
| `AI_Usage_Hours_Per_Day` | Horas de uso por dia |
| `Task_Performed` | Tarea realizada |
| `Monthly_AI_Cost` | Costo mensual |
| `Productivity_Score` | Puntaje de productividad |
| `Accuracy_Rating` |  |
| `Satisfaction_Score` | Puntaje de satisfaccion |
| `Time_Saved_Hours_Per_Week` | Horas ahorradas por semana |
| `Work_or_Study_Hours_Per_Day` | Horas de trabajo o estudio por dia |
| `Would_Recommend` | Recomiendan o no el uso de IA |

In [29]:
df = pd.read_csv("AI_Usage_and_Impact_on_Students_and_Professionals.csv")

### Realizamos el EDA

In [4]:
df

,User_ID,Age,Gender,Country,User_Type,Education_Level,Profession,Monthly_Income,AI_Tool,AI_Purpose,AI_Usage_Hours_Per_Day,Tasks_Performed,Monthly_AI_Cost,Productivity_Score,Accuracy_Rating,Satisfaction_Score,Time_Saved_Hours_Per_Week,Work_or_Study_Hours_Per_Day,Would_Recommend
0,U0269,30,Male,United Kingdom,Professional,Master's,Business Analyst,5421,ChatGPT,Office Work,2 hrs,Data analysis using AI-powered analytics tools...,NaN,5.3,4.0,7.0,3.9,7.3,Yes
1,U0217,30,Male,United States,Professional,Bachelor's,Customer Support Specialist,8903,ChatGPT,Customer Support,5.7,Resolving customer inquiries using AI chatbot ...,0,9.9,3.0,9.0,11.4,8.4 hrs,Yes
2,U0152,17,Male,Canada,Student,NaN,Computer Science Student,402,Chat GPT,Coding,1 hrs,NaN,20,3.2,2.0,4.0,5.2,6.7,No
3,U0264,35,FEMALE,Brazil,Professional,Bachelor's,Desenvolvedora de Software / Software Developer,1367,Meta AI,Coding,1.7,"Usar GitHub Copilot para autocompletar código,...",20,5.6,4.0,5.0,6.4,9.6,Maybe
4,U0263,19,Female,Canada,Student,Undergraduate,Biology Student,438,Perplexity AI,NaN,4.1,Using AI to generate study summaries for exam ...,0,4.7,4.0,7.0,9.2,6.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,U0066,NaN,Female,United States,Professional,Bachelor's,NaN,8255,Microsoft Copilot,NaN,1.8,"Code debugging with AI pair programming tools,...",0,1.8,3.0,4.0,NaN,12.2,No
296,U0094,43,Male,Nigeria,Professional,Diploma,Multimedia Content Producer,NaN,ChatGPT,Content Creation,1.2,Writing blog articles with AI writing assistan...,0,4.7,3.0,NaN,1,10.9,No
297,U0136,48,Male,Brazil,Professional,Diploma,Desenvolvedor de Sistemas (Systems Developer),544,Google Gemini,Coding,5.5,"Code debugging and optimization with AI tools,...",0,7.8,4.0,7.0,11.5,8.4,Yes
298,U0002,31,Female,Pakistan,Professional,Diploma,Junior Software Developer,448,ChatGPT,Coding,0.7 hrs,"Automated code generation using AI assistants,...",0,4.3,3.0,4.0,1.7,9.5,No
299,U0130,36 yrs,Male,United States,Professional,Diploma,Software Developer,6766,Chat GPT,Coding,2.8,"Debugging code with AI-assisted analysis, gene...",0,5.4,4.0,7.0,6.2,8.2,Yes

In [24]:
print(f'Filas: {df.shape[0]}') 
print(f'Columnas: {df.shape[1]}')
df.info()
#df.describe() 
#df.describe(include=object)

Filas: 300
Columnas: 19
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      300 non-null    object
 1   age                          277 non-null    object
 2   gender                       290 non-null    object
 3   country                      290 non-null    object
 4   user_type                    300 non-null    object
 5   education_level              287 non-null    object
 6   profession                   285 non-null    object
 7   monthly_income               290 non-null    object
 8   ai_tool                      289 non-null    object
 9   ai_purpose                   287 non-null    object
 10  ai_usage_hours_per_day       293 non-null    object
 11  tasks_performed              282 non-null    object
 12  monthly_ai_cost              288 non-null    object
 13  productivity_score           284 non-null    float64
 14  accuracy_rating              285 non-null    float64
 15  satisfaction_score           293 non-null    float64
 16  time_saved_hours_per_week    290 non-null    object
 17  work_or_study_hours_per_day  291 non-null    object
 18  would_recommend              295 non-null    object
dtypes: float64(3), object(16)
memory usage: 44.7+ KB

### Normalizar variables

In [31]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ","_", regex=False)
)

In [32]:
df["age"] = pd.to_numeric(df["age"], errors= "coerce")
df["monthly_income"] = df["monthly_income"].str.replace("$","", regex=False).str.replace(",","", regex=False)
df["monthly_income"] = pd.to_numeric(df["monthly_income"], errors="coerce")

df["ai_usage_hours_per_day"] = df["ai_usage_hours_per_day"].str.replace("hrs","", regex=False)
df["ai_usage_hours_per_day"] = pd.to_numeric(df["ai_usage_hours_per_day"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      300 non-null    object
 1   age                          263 non-null    float64
 2   gender                       290 non-null    object
 3   country                      290 non-null    object
 4   user_type                    300 non-null    object
 5   education_level              287 non-null    object
 6   profession                   285 non-null    object
 7   monthly_income               290 non-null    float64
 8   ai_tool                      289 non-null    object
 9   ai_purpose                   287 non-null    object
 10  ai_usage_hours_per_day       293 non-null    float64
 11  tasks_performed              282 non-null    object
 12  monthly_ai_cost              288 non-null    object
 13  productivity_score           284 non-null    float64
 14  accuracy_rating              285 non-null    float64
 15  satisfaction_score           293 non-null    float64
 16  time_saved_hours_per_week    290 non-null    object
 17  work_or_study_hours_per_day  291 non-null    object
 18  would_recommend              295 non-null    object
dtypes: float64(6), object(13)
memory usage: 44.7+ KB

In [33]:
df["monthly_ai_cost"] = df["monthly_ai_cost"].str.replace("$","", regex=False)
df["monthly_ai_cost"]= pd.to_numeric(df["monthly_ai_cost"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      300 non-null    object
 1   age                          263 non-null    float64
 2   gender                       290 non-null    object
 3   country                      290 non-null    object
 4   user_type                    300 non-null    object
 5   education_level              287 non-null    object
 6   profession                   285 non-null    object
 7   monthly_income               290 non-null    float64
 8   ai_tool                      289 non-null    object
 9   ai_purpose                   287 non-null    object
 10  ai_usage_hours_per_day       293 non-null    float64
 11  tasks_performed              282 non-null    object
 12  monthly_ai_cost              288 non-null    float64
 13  productivity_score           284 non-null    float64
 14  accuracy_rating              285 non-null    float64
 15  satisfaction_score           293 non-null    float64
 16  time_saved_hours_per_week    290 non-null    object
 17  work_or_study_hours_per_day  291 non-null    object
 18  would_recommend              295 non-null    object
dtypes: float64(7), object(12)
memory usage: 44.7+ KB

In [34]:
df["time_saved_hours_per_week"] = df["time_saved_hours_per_week"].str.replace("hrs","", regex=False)
df["time_saved_hours_per_week"] = pd.to_numeric(df["time_saved_hours_per_week"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      300 non-null    object
 1   age                          263 non-null    float64
 2   gender                       290 non-null    object
 3   country                      290 non-null    object
 4   user_type                    300 non-null    object
 5   education_level              287 non-null    object
 6   profession                   285 non-null    object
 7   monthly_income               290 non-null    float64
 8   ai_tool                      289 non-null    object
 9   ai_purpose                   287 non-null    object
 10  ai_usage_hours_per_day       293 non-null    float64
 11  tasks_performed              282 non-null    object
 12  monthly_ai_cost              288 non-null    float64
 13  productivity_score           284 non-null    float64
 14  accuracy_rating              285 non-null    float64
 15  satisfaction_score           293 non-null    float64
 16  time_saved_hours_per_week    290 non-null    float64
 17  work_or_study_hours_per_day  291 non-null    object
 18  would_recommend              295 non-null    object
dtypes: float64(8), object(11)
memory usage: 44.7+ KB

In [35]:
df["work_or_study_hours_per_day"] = df["work_or_study_hours_per_day"].str.replace("hrs","", regex=False)
df["work_or_study_hours_per_day"]= pd.to_numeric(df["work_or_study_hours_per_day"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   user_id                      300 non-null    object
 1   age                          263 non-null    float64
 2   gender                       290 non-null    object
 3   country                      290 non-null    object
 4   user_type                    300 non-null    object
 5   education_level              287 non-null    object
 6   profession                   285 non-null    object
 7   monthly_income               290 non-null    float64
 8   ai_tool                      289 non-null    object
 9   ai_purpose                   287 non-null    object
 10  ai_usage_hours_per_day       293 non-null    float64
 11  tasks_performed              282 non-null    object
 12  monthly_ai_cost              288 non-null    float64
 13  productivity_score           284 non-null    float64
 14  accuracy_rating              285 non-null    float64
 15  satisfaction_score           293 non-null    float64
 16  time_saved_hours_per_week    290 non-null    float64
 17  work_or_study_hours_per_day  291 non-null    float64
 18  would_recommend              295 non-null    object
dtypes: float64(9), object(10)
memory usage: 44.7+ KB

In [43]:
df.duplicated().sum()
df[df.duplicated(keep=False)].sort_values(by="user_id")

,user_id,age,gender,country,user_type,education_level,profession,monthly_income,ai_tool,ai_purpose,ai_usage_hours_per_day,tasks_performed,monthly_ai_cost,productivity_score,accuracy_rating,satisfaction_score,time_saved_hours_per_week,work_or_study_hours_per_day,would_recommend
235,U0055,30.0,Male,Philippines,Professional,Masters,Senior Software Engineer,579.0,Microsoft Copilot,Coding,3.8,Code review and optimization using AI assistan...,0.0,6.1,4.0,6.0,9.4,7.4,Maybe
85,U0055,30.0,Male,Philippines,Professional,Masters,Senior Software Engineer,579.0,Microsoft Copilot,Coding,3.8,Code review and optimization using AI assistan...,0.0,6.1,4.0,6.0,9.4,7.4,Maybe
16,U0059,22.0,Male,Canada,Professional,High School,Customer Service Representative,3546.0,Perplexity AI,Customer Support,1.7,Responding to customer inquiries via AI chatbo...,0.0,7.0,4.0,7.0,3.4,6.7,Yes
87,U0059,22.0,Male,Canada,Professional,High School,Customer Service Representative,3546.0,Perplexity AI,Customer Support,1.7,Responding to customer inquiries via AI chatbo...,0.0,7.0,4.0,7.0,3.4,6.7,Yes
251,U0085,17.0,Female,Canada,Student,PhD,Theoretical Physics Student,518.0,NaN,Studying,3.2,Generating practice problems for quantum mecha...,20.0,5.2,4.0,8.0,4.8,20.0,Yes
161,U0085,17.0,Female,Canada,Student,PhD,Theoretical Physics Student,518.0,NaN,Studying,3.2,Generating practice problems for quantum mecha...,20.0,5.2,4.0,8.0,4.8,20.0,Yes
159,U0104,26.0,Male,Pakistan,Student,NaN,Mechanical Engineering Student,54.0,ChatGPT,Research,2.7,"Literature review automation, research paper s...",20.0,NaN,3.0,5.0,5.0,6.9,Maybe
271,U0104,26.0,Male,Pakistan,Student,NaN,Mechanical Engineering Student,54.0,ChatGPT,Research,2.7,"Literature review automation, research paper s...",20.0,NaN,3.0,5.0,5.0,6.9,Maybe
67,U0116,20.0,Male,India,Student,Undergraduate,Digital Media and Communications Student,79.0,Google Gemini,Content Creation,3.5,"AI-assisted blog writing and SEO optimization,...",20.0,4.7,4.0,7.0,8.3,6.2,Yes
63,U0116,20.0,Male,India,Student,Undergraduate,Digital Media and Communications Student,79.0,Google Gemini,Content Creation,3.5,"AI-assisted blog writing and SEO optimization,...",20.0,4.7,4.0,7.0,8.3,6.2,Yes
170,U0138,NaN,Female,Canada,Student,Master's,NaN,324.0,Microsoft Copilot,Coding,7.1,NaN,20.0,NaN,2.0,5.0,11.6,3.0,No
15,U0138,NaN,Female,Canada,Student,Master's,NaN,324.0,Microsoft Copilot,Coding,7.1,NaN,20.0,NaN,2.0,5.0,11.6,3.0,No
187,U0151,39.0,Female,India,Professional,Master's,Senior Software Developer,1106.0,Microsoft Copilot,Coding,4.4,"Code review and debugging using AI assistants,...",0.0,6.1,4.0,8.0,7.7,6.4,Yes
238,U0151,39.0,Female,India,Professional,Master's,Senior Software Developer,1106.0,Microsoft Copilot,Coding,4.4,"Code review and debugging using AI assistants,...",0.0,6.1,4.0,8.0,7.7,6.4,Yes
108,U0188,27.0,Male,France,Student,High School,History Student,482.0,DeepSeek,Research,6.0,"Literature review and document summarization, ...",0.0,7.6,5.0,8.0,13.1,6.8,Yes
268,U0188,27.0,Male,France,Student,High School,History Student,482.0,DeepSeek,Research,6.0,"Literature review and document summarization, ...",0.0,7.6,5.0,8.0,13.1,6.8,Yes
130,U0244,26.0,Female,United States,Student,Master's,Data Science Student,520.0,ChatGPT,Studying,2.7,"Generating practice problem sets, debugging Py...",0.0,5.7,4.0,7.0,8.4,5.4,Yes
137,U0244,26.0,Female,United States,Student,Master's,Data Science Student,520.0,ChatGPT,Studying,2.7,"Generating practice problem sets, debugging Py...",0.0,5.7,4.0,7.0,8.4,5.4,Yes
80,U0254,46.0,Female,United Kingdom,Professional,Bachelor's,Customer Support Manager,3159.0,Perplexity AI,Customer Support,1.9,Using AI chatbots to handle routine customer i...,0.0,3.4,NaN,7.0,4.1,8.6,Yes
179,U0254,46.0,Female,United Kingdom,Professional,Bachelor's,Customer Support Manager,3159.0,Perplexity AI,Customer Support,1.9,Using AI chatbots to handle routine customer i...,0.0,3.4,NaN,7.0,4.1,8.6,Yes
164,U0279,35.0,Male,Australia,Professional,Bachelor's,Senior Software Developer,6399.0,ChatGPT,Coding,1.3,"Code review and debugging using AI assistants,...",20.0,3.1,3.0,4.0,4.3,8.1,No
100,U0279,35.0,Male,Australia,Professional,Bachelor's,Senior Software Developer,6399.0,ChatGPT,Coding,1.3,"Code review and debugging using AI assistants,...",20.0,3.1,3.0,4.0,4.3,8.1,No
202,U0280,NaN,Female,Brazil,Student,Master's,Software Engineering Student,82.0,Google Gemini,Coding,0.8,"Debugging Python code with AI assistance, gene...",0.0,2.1,4.0,6.0,1.2,8.3,Yes
267,U0280,NaN,Female,Brazil,Student,Master's,Software Engineering Student,82.0,Google Gemini,Coding,0.8,"Debugging Python code with AI assistance, gene...",0.0,2.1,4.0,6.0,1.2,8.3,Yes

In [ ]:
df_limpio = df.drop_duplicates()

In [47]:
df.isnull().sum().sort_values(ascending=False)

age                            37
tasks_performed                18
productivity_score             16
profession                     15
accuracy_rating                15
ai_purpose                     13
education_level                13
monthly_ai_cost                12
ai_tool                        11
time_saved_hours_per_week      10
gender                         10
country                        10
monthly_income                 10
work_or_study_hours_per_day     9
satisfaction_score              7
ai_usage_hours_per_day          7
would_recommend                 5
user_id                         0
user_type                       0
dtype: int64

In [ ]:
df_limpio = df.dropna()